name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-05"

# compatibility_flags = [ "nodejs_compat" ]

 [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiY2VhYWYwYzUtNGRlMi00MjJiLTlmM2ItOGZiNDIxMmMyMDdkIiwidGVuYW50X2lkIjoiMTdhYjc5YjAyMDJhZjY4M2I4Zjg2ZTc3MGRkNWRiZDY5MmFjM2I3Zjc1NTI1NGNmNzZmNjFlOGFmMzg5Yzg4ZiIsImludGVybmFsX3NlY3JldCI6Ijc4MzRjZWNhLTQ1NjktNDE3MS04M2U1LWY2Y2ZhOTE2NmYxOSJ9.70SQQToLaqvGAUQIx933eyQbV0zC_zdjgvhJ3u-8HnU"

JWT_SECRET_KEY="mysuperkey"